package com.example.constants

object BuildConfig {
    const val WIKI_API_TOKEN = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGkiOjIsImdycCI6MSwiaWF0IjoxNjU5NTkwNzk3LCJleHAiOjE3NTQyNjM1OTcsImF1ZCI6InVybjp3aWtpLmpzIiwiaXNzIjoidXJuOndpa2kuanMifQ.nTTg5bZLhe67cYJh8SvjWDE152MgOmvf25cxDFeyUOUx3WkPpElK8QRqWIhMenemBWOVtp3sMZkRyNDywpYNZcV5XNTnXzeypL7DQhcEWCd7lDJoIt8Oq5jyJP3v9_GYKr9qKGKU9LTg9Uo8Ek9fqrroU39w-z_fwCxJ0YClFWeC7Xpo2QgcLgYVDKE_qUruYUDb7xiUhWIFKeWi59pLSXux8PYOUGRIJJCkypalLnnbKaV-MIE9a4oUXYWACX-hXh8p0pclDa-DWoQSRFRS_CmYzqLrHzodsXeqsrRCwHO2g8_HtKC40YsyN93FnB430y7wamCaWu8yjQE47rCYDA"

    const val WIKI_BASE_URL = "https://wiki.csd.moe/graphql"

    const val PIC_BED_BASE_URL = "https://picbed.net/"


    const val IP_PARSE_URL = "https://ip.useragentinfo.com/json"

    /**春哥*/
    const val WIKI_URL = "https://wiki.whi.ink/graphql"
    const val WIKI_TOKEN = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGkiOjEsImdycCI6MSwiaWF0IjoxNjU5OTY0ODQzLCJleHAiOjE2OTE1MjI0NDMsImF1ZCI6InVybjp3aWtpLmpzIiwiaXNzIjoidXJuOndpa2kuanMifQ.LeB5Qq25_2LIKHgCMqQECh-5LXhuAa9P4REjtICbtoW2MaRWaGWdLASy5r8ibtKfouIdIb2O7z0pIZYp78HOZN3p1W5hzlghWogOulz-p4mVlpfXk00Rct-qYYyzoZIKGd2Hox7yX5NnEGlwWsi0L1N46uIxjFaIGyhMxYSOm9mX5y4yVjqVllmTwkLlszVbXhfNmFnx7d0Ti7DoUb-a6LcB7XDYqR1zh6cIIAkec3UZ4wQSn5Z7dtjdbDDost_lat4uUghAy9KXnGdYvnnuCIiZnhEtwIYrTj2rnmxoawnCL0PS5BZb-3tDldivyrCy7Dv1uIQ3LEoowDveteXRjA"
}